name: $(Build.SourceVersion)
jobs:
- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: .ci/use-node.yml
  - template: .ci/run-validation-test.yml

- job: MacOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: .ci/use-node.yml
  - template: .ci/run-validation-test.yml

- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: .ci/use-node.yml
  - template: .ci/run-validation-test.yml
