name: $(Build.SourceVersion)
jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: .ci/use-node.yml
  - template: .ci/run-validation-test.yml

- job: MacOS
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - template: .ci/use-node.yml
  - template: .ci/run-validation-test.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/use-node.yml
  - template: .ci/run-validation-test.yml
