SET(CMAKE_SYSTEM_NAME Windows)
#this one not so much
#SET(CMAKE_SYSTEM_VERSION 1)

# where is the target environment
SET(PREFIX x86_64-w64-mingw32)
SET(CMAKE_FIND_ROOT_PATH /usr/${PREFIX}/sys-root/mingw)
SET(TOOLCHAIN_PATH ${CMAKE_SYSROOT}/bin)

 
# specify the cross compiler
SET(CMAKE_MAKE_PROGRAM mingw32-make)
SET(CMAKE_C_COMPILER   ${PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${PREFIX}-g++)
SET(CMAKE_AR ${PREFIX}-gcc-ar)
SET(CMAKE_NM ${PREFIX}-gcc-nm)
SET(CMAKE_RC_COMPILER  ${PREFIX}-windres)

# specify the cross linker
SET(CMAKE_RANLIB ${PREFIX}-gcc-ranlib)
SET(CMAKE_C_COMPILER_WORKS 1)
SET(CMAKE_CXX_COMPILER_WORKS 1)
SET(CMAKE_SYSTEM_PROCESSOR "x86_64")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
